<?php


class PeclHttpTransport implements TransportInterface {
    /**
     * @param Proxy $proxy
     * @return mixed HTTP response code
     */
    public function send($proxy) {
        $responseCode = null;
        $responseText = null;

        $headers = $proxy->getHeaders();

        // Remove "Host" header; it will be generated by client
        if (array_key_exists('Host', $headers)) {
            unset($headers['Host']);
        }

        $request = (new http\Client\Request(
            'POST',
            $proxy->getEndpointUrl(),
            $headers,
            (new http\Message())
                ->getBody()
                ->append($proxy->getBody())
        ));

        $timeoutSeconds = $proxy->getTimeoutSeconds();
        if ($timeoutSeconds != null) {
            $request->setOptions([
                'timeout' => $timeoutSeconds
            ]);
        }

        $response = (new http\Client)
            ->enqueue($request)
            ->send()
            ->getResponse($request);

        $responseCode = $response->getResponseCode();
        $responseText = $responseCode;
    }
}